/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: addressbook.proto */

#ifndef PROTOBUF_C_addressbook_2eproto__INCLUDED
#define PROTOBUF_C_addressbook_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Tutorial__Person Tutorial__Person;
typedef struct _Tutorial__Person__PhoneNumber Tutorial__Person__PhoneNumber;
typedef struct _Tutorial__AddressBook Tutorial__AddressBook;


/* --- enums --- */

typedef enum _Tutorial__Person__PhoneType {
  TUTORIAL__PERSON__PHONE_TYPE__MOBILE = 0,
  TUTORIAL__PERSON__PHONE_TYPE__HOME = 1,
  TUTORIAL__PERSON__PHONE_TYPE__WORK = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TUTORIAL__PERSON__PHONE_TYPE)
} Tutorial__Person__PhoneType;

/* --- messages --- */

struct  _Tutorial__Person__PhoneNumber
{
  ProtobufCMessage base;
  char *number;
  Tutorial__Person__PhoneType type;
};
#define TUTORIAL__PERSON__PHONE_NUMBER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tutorial__person__phone_number__descriptor) \
    , (char *)protobuf_c_empty_string, TUTORIAL__PERSON__PHONE_TYPE__MOBILE }


/*
 * [START messages]
 */
struct  _Tutorial__Person
{
  ProtobufCMessage base;
  char *name;
  /*
   * Unique ID number for this person.
   */
  int32_t id;
  char *email;
  size_t n_phones;
  Tutorial__Person__PhoneNumber **phones;
};
#define TUTORIAL__PERSON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tutorial__person__descriptor) \
    , (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0,NULL }


/*
 * Our address book file is just one of these.
 */
struct  _Tutorial__AddressBook
{
  ProtobufCMessage base;
  size_t n_people;
  Tutorial__Person **people;
};
#define TUTORIAL__ADDRESS_BOOK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tutorial__address_book__descriptor) \
    , 0,NULL }


/* Tutorial__Person__PhoneNumber methods */
void   tutorial__person__phone_number__init
                     (Tutorial__Person__PhoneNumber         *message);
/* Tutorial__Person methods */
void   tutorial__person__init
                     (Tutorial__Person         *message);
size_t tutorial__person__get_packed_size
                     (const Tutorial__Person   *message);
size_t tutorial__person__pack
                     (const Tutorial__Person   *message,
                      uint8_t             *out);
size_t tutorial__person__pack_to_buffer
                     (const Tutorial__Person   *message,
                      ProtobufCBuffer     *buffer);
Tutorial__Person *
       tutorial__person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tutorial__person__free_unpacked
                     (Tutorial__Person *message,
                      ProtobufCAllocator *allocator);
/* Tutorial__AddressBook methods */
void   tutorial__address_book__init
                     (Tutorial__AddressBook         *message);
size_t tutorial__address_book__get_packed_size
                     (const Tutorial__AddressBook   *message);
size_t tutorial__address_book__pack
                     (const Tutorial__AddressBook   *message,
                      uint8_t             *out);
size_t tutorial__address_book__pack_to_buffer
                     (const Tutorial__AddressBook   *message,
                      ProtobufCBuffer     *buffer);
Tutorial__AddressBook *
       tutorial__address_book__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tutorial__address_book__free_unpacked
                     (Tutorial__AddressBook *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Tutorial__Person__PhoneNumber_Closure)
                 (const Tutorial__Person__PhoneNumber *message,
                  void *closure_data);
typedef void (*Tutorial__Person_Closure)
                 (const Tutorial__Person *message,
                  void *closure_data);
typedef void (*Tutorial__AddressBook_Closure)
                 (const Tutorial__AddressBook *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor tutorial__person__descriptor;
extern const ProtobufCMessageDescriptor tutorial__person__phone_number__descriptor;
extern const ProtobufCEnumDescriptor    tutorial__person__phone_type__descriptor;
extern const ProtobufCMessageDescriptor tutorial__address_book__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_addressbook_2eproto__INCLUDED */
